// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDYbDbbE7WL4_4Qk9fMi9DOd8slTYM4nw',
    appId: '1:455781150466:web:488128545af6a7aa755c1b',
    messagingSenderId: '455781150466',
    projectId: 'sao-camilo-pi',
    authDomain: 'sao-camilo-pi.firebaseapp.com',
    databaseURL: 'https://sao-camilo-pi-default-rtdb.firebaseio.com',
    storageBucket: 'sao-camilo-pi.appspot.com',
    measurementId: 'G-3F5CF9NJ4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFkRJ9YCxkacOlDk-JB6zHBeNrAyFGxk',
    appId: '1:455781150466:android:a2c0499e6a20daa5755c1b',
    messagingSenderId: '455781150466',
    projectId: 'sao-camilo-pi',
    databaseURL: 'https://sao-camilo-pi-default-rtdb.firebaseio.com',
    storageBucket: 'sao-camilo-pi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMg_LESHk1NQVbzRyPP3dNaCX_RZU6o-0',
    appId: '1:455781150466:ios:09b234b3eebc3aac755c1b',
    messagingSenderId: '455781150466',
    projectId: 'sao-camilo-pi',
    databaseURL: 'https://sao-camilo-pi-default-rtdb.firebaseio.com',
    storageBucket: 'sao-camilo-pi.appspot.com',
    iosBundleId: 'com.example.scGestaoDeSaude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMg_LESHk1NQVbzRyPP3dNaCX_RZU6o-0',
    appId: '1:455781150466:ios:09b234b3eebc3aac755c1b',
    messagingSenderId: '455781150466',
    projectId: 'sao-camilo-pi',
    databaseURL: 'https://sao-camilo-pi-default-rtdb.firebaseio.com',
    storageBucket: 'sao-camilo-pi.appspot.com',
    iosBundleId: 'com.example.scGestaoDeSaude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDYbDbbE7WL4_4Qk9fMi9DOd8slTYM4nw',
    appId: '1:455781150466:web:59c35dc9aab9a2b7755c1b',
    messagingSenderId: '455781150466',
    projectId: 'sao-camilo-pi',
    authDomain: 'sao-camilo-pi.firebaseapp.com',
    databaseURL: 'https://sao-camilo-pi-default-rtdb.firebaseio.com',
    storageBucket: 'sao-camilo-pi.appspot.com',
    measurementId: 'G-SSDDRXQV0H',
  );
}
